name: fajr
description: FajrToIsha - Islamic prayer times, Quran, Qibla, and masjid finder app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  geolocator: ^13.0.2
  intl: ^0.19.0
  google_fonts: ^6.2.1
  flutter_compass: ^0.8.1
  shared_preferences: ^2.3.0
  url_launcher: ^6.2.5
  audioplayers: ^6.1.0
  flutter_local_notifications: ^17.2.4
  timezone: ^0.9.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
